name: Workflow 3

on:
  workflow_call:

jobs:
  show-index:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Print index.js
        run: cat dist/index.js
        
run-workflow-4:
    needs: show-index
    uses: ./.github/workflows/workflow4.yml
